device: "auto"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.StoiMetric
    sample_rate: 16000
    device: ${metrics.device}
    name: "STOI"
#  - _target_: src.metrics.NISQAMetric
#    sample_rate: 16000
#    device: ${metrics.device}
#    name: "NISQA"
