defaults:
  - model: soundstream
  - writer: cometml
  - metrics: audio
  - datasets: librispeech
  - dataloader: librispeech
  - transforms: librispeech
  - _self_
generator_criterion:
  _target_: src.loss.GeneratorLoss

discriminator_criterion:
  _target_: src.loss.DiscriminatorLoss

generator_optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  betas: [0.5, 0.9]

discriminator_optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  betas: [0.5, 0.9]


generator_lr_scheduler: null

discriminator_lr_scheduler: null

trainer:
  log_step: 25
  n_epochs: 90
  epoch_len: 500
  device_tensors: ["data_object"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
